import { Workflow } from './workflow-schema'

export const workflowTemplates: Workflow[] = [
  {
    id: 'wf1',
    name: 'Hiring Process',
    description: 'Complete hiring workflow for engineering positions',
    status: 'active',
    createdAt: new Date('2024-03-01'),
    createdBy: 'Alex Thompson',
    steps: [
      {
        id: 'step1',
        name: 'Job Application',
        description: 'Collect candidate information',
        order: 1,
        emailTrigger: true,
        fields: [
          { id: 'f1', name: 'Full Name', type: 'text', required: true, order: 1 },
          { id: 'f2', name: 'Email', type: 'text', required: true, order: 2 },
          { id: 'f3', name: 'Phone', type: 'text', required: false, order: 3 },
          { id: 'f4', name: 'Resume', type: 'file', required: true, order: 4 },
        ],
        deadline: 7,
        assignedRole: 'HR Manager',
      },
      {
        id: 'step2',
        name: 'Initial Screening',
        description: 'Screen candidates',
        order: 2,
        emailTrigger: true,
        fields: [
          { id: 'f1', name: 'Screening Notes', type: 'textarea', required: false, order: 1 },
          {
            id: 'f2',
            name: 'Technical Level',
            type: 'select',
            required: true,
            order: 2,
            options: ['Junior', 'Mid-Level', 'Senior'],
          },
          { id: 'f3', name: 'Approved', type: 'checkbox', required: true, order: 3 },
        ],
        deadline: 3,
        assignedRole: 'Hiring Manager',
      },
      {
        id: 'step3',
        name: 'Technical Interview',
        description: 'Technical assessment interview',
        order: 3,
        emailTrigger: true,
        fields: [
          {
            id: 'f1',
            name: 'Interview Date',
            type: 'date',
            required: true,
            order: 1,
          },
          {
            id: 'f2',
            name: 'Technical Score',
            type: 'number',
            required: true,
            order: 2,
          },
          { id: 'f3', name: 'Feedback', type: 'textarea', required: false, order: 3 },
        ],
        deadline: 5,
        assignedRole: 'Technical Lead',
      },
      {
        id: 'step4',
        name: 'HR Round',
        description: 'HR discussion and benefits review',
        order: 4,
        emailTrigger: true,
        fields: [
          { id: 'f1', name: 'Salary Expectations', type: 'text', required: true, order: 1 },
          {
            id: 'f2',
            name: 'Start Date Preference',
            type: 'date',
            required: true,
            order: 2,
          },
          { id: 'f3', name: 'Notes', type: 'textarea', required: false, order: 3 },
        ],
        deadline: 3,
        assignedRole: 'HR Manager',
      },
      {
        id: 'step5',
        name: 'Offer Stage',
        description: 'Send offer letter and finalize',
        order: 5,
        emailTrigger: true,
        fields: [
          { id: 'f1', name: 'Offer Letter', type: 'file', required: true, order: 1 },
          { id: 'f2', name: 'Offer Accepted', type: 'checkbox', required: true, order: 2 },
        ],
        deadline: 7,
        assignedRole: 'HR Manager',
      },
    ],
    candidateCount: 12,
  },
  {
    id: 'wf2',
    name: 'Sales Process',
    description: 'Sales qualification and deal management workflow',
    status: 'active',
    createdAt: new Date('2024-02-15'),
    createdBy: 'Jennifer White',
    steps: [
      {
        id: 'step1',
        name: 'Lead Qualification',
        description: 'Qualify incoming leads',
        order: 1,
        emailTrigger: true,
        fields: [
          { id: 'f1', name: 'Company Name', type: 'text', required: true, order: 1 },
          { id: 'f2', name: 'Contact Name', type: 'text', required: true, order: 2 },
          { id: 'f3', name: 'Industry', type: 'select', required: true, order: 3 },
          { id: 'f4', name: 'Budget', type: 'number', required: false, order: 4 },
        ],
        deadline: 2,
        assignedRole: 'Sales Rep',
      },
      {
        id: 'step2',
        name: 'Demo Scheduled',
        description: 'Schedule product demo',
        order: 2,
        emailTrigger: true,
        fields: [
          { id: 'f1', name: 'Demo Date', type: 'date', required: true, order: 1 },
          { id: 'f2', name: 'Attendees', type: 'text', required: true, order: 2 },
        ],
        deadline: 5,
        assignedRole: 'Sales Rep',
      },
      {
        id: 'step3',
        name: 'Proposal Sent',
        description: 'Send proposal to client',
        order: 3,
        emailTrigger: true,
        fields: [
          { id: 'f1', name: 'Proposal Document', type: 'file', required: true, order: 1 },
          { id: 'f2', name: 'Deal Value', type: 'number', required: true, order: 2 },
        ],
        deadline: 10,
        assignedRole: 'Sales Manager',
      },
      {
        id: 'step4',
        name: 'Negotiation',
        description: 'Negotiate terms and pricing',
        order: 4,
        emailTrigger: false,
        fields: [
          { id: 'f1', name: 'Final Price', type: 'number', required: true, order: 1 },
          { id: 'f2', name: 'Terms Agreed', type: 'checkbox', required: true, order: 2 },
        ],
        deadline: 7,
        assignedRole: 'Sales Manager',
      },
    ],
    candidateCount: 8,
  },
  {
    id: 'wf3',
    name: 'Onboarding Workflow',
    status: 'active',
    description: 'New hire onboarding and setup process',
    createdAt: new Date('2024-01-20'),
    createdBy: 'David Lee',
    steps: [
      {
        id: 'step1',
        name: 'Pre-Onboarding',
        description: 'Setup before employee starts',
        order: 1,
        emailTrigger: true,
        fields: [
          { id: 'f1', name: 'Start Date', type: 'date', required: true, order: 1 },
          { id: 'f2', name: 'Equipment Needed', type: 'textarea', required: false, order: 2 },
        ],
        deadline: 5,
        assignedRole: 'HR Manager',
      },
      {
        id: 'step2',
        name: 'First Day',
        description: 'Orientation and welcome',
        order: 2,
        emailTrigger: true,
        fields: [
          { id: 'f1', name: 'Welcome Kit Sent', type: 'checkbox', required: true, order: 1 },
          { id: 'f2', name: 'Orientation Notes', type: 'textarea', required: false, order: 2 },
        ],
        deadline: 1,
        assignedRole: 'Team Lead',
      },
      {
        id: 'step3',
        name: 'Training',
        description: 'Role-specific training',
        order: 3,
        emailTrigger: false,
        fields: [
          { id: 'f1', name: 'Training Completed', type: 'checkbox', required: true, order: 1 },
          { id: 'f2', name: 'Modules Completed', type: 'textarea', required: true, order: 2 },
        ],
        deadline: 14,
        assignedRole: 'Team Lead',
      },
      {
        id: 'step4',
        name: '30-Day Check-in',
        description: 'First month review',
        order: 4,
        emailTrigger: false,
        fields: [
          { id: 'f1', name: 'Performance Notes', type: 'textarea', required: true, order: 1 },
          {
            id: 'f2',
            name: 'Feedback',
            type: 'select',
            required: true,
            order: 2,
            options: ['Excellent', 'Good', 'Needs Improvement'],
          },
        ],
        deadline: 30,
        assignedRole: 'Manager',
      },
      {
        id: 'step5',
        name: '90-Day Review',
        description: 'Three-month evaluation',
        order: 5,
        emailTrigger: false,
        fields: [
          { id: 'f1', name: 'Evaluation Score', type: 'number', required: true, order: 1 },
          { id: 'f2', name: 'Approved for Confirmation', type: 'checkbox', required: true, order: 2 },
        ],
        deadline: 90,
        assignedRole: 'Manager',
      },
      {
        id: 'step6',
        name: 'Confirmation',
        description: 'Employee confirmation',
        order: 6,
        emailTrigger: true,
        fields: [
          { id: 'f1', name: 'Confirmed', type: 'checkbox', required: true, order: 1 },
        ],
        deadline: 0,
        assignedRole: 'HR Manager',
      },
    ],
    candidateCount: 0,
  },
]
